### ISSUE TITLE
[FEATURE/BE] 이미지 저장용 S3 서버 구축

### ISSUE THREAD

**Issue by ja960508** [woowa-techcamp-2022/web-fleamarket-6#19]
## 🔨 요구 사항 
이미지 저장을 위한 S3 서버를 설정, 구축한다.

## 📝 완료 조건 
- [x] AWS S3 서버 구축
- [x] S3 서버 테스트

## ⏰ 예상소요시간
1h 30m

**Comment by KimKwon** [comment]
실제 작업 완료시간: 3H

S3 환경설정 및 SDK 연결작업이 처음이라 조금 헤맸다.
