### ISSUE TITLE
[FEATURE/FE] 폰트, 단위등 디테일한 부분 교정

### ISSUE THREAD

**Issue by KimKwon** [woowa-techcamp-2022/web-fleamarket-6#74]
## 🔨 요구 사항 

단위, 폰트 등 정돈되지 않은 부분들을 정리해요.

## 📝 완료 조건 

- [x] 모든 price가 localestring으로 나타나도록해요.
- [x] 폰트, 색상등 정리되지 않은 부분들을 정리해요.

## ⏰ 예상소요시간

1h

**Comment by ja960508** [comment]
localString으로 변경하는 작업 하려고 했었는데 처리하쎴네요!! 감사합니다~
